// biome-ignore-all lint/performance/noBarrelFile: this barrel is the schema. drizzle-kit, Drizzle's relational queries and Better Auth's adapter all take every table as one module.
// biome-ignore-all lint/performance/noReExportAll: a new table in either file has to join the schema without anyone remembering to list it here.
//
// One schema object for both drizzle-kit and the Better Auth adapter.
//
// `auth.ts` is generated by `npm run auth:schema` and is kept in its own file so
// regenerating it can never clobber the hand-written app tables.
export * from './app';
export * from './auth';
